Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true NO GUI for this stupid box
    vb.memory = "512"
    vb.cpus = 1
    vb.name = "Vagrant-virtual-machine"
  end
  config.vm.hostname = "denisa"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git
    sudo apt-get install -y python-pip python-dev build-essential
    sudo apt-get -y autoremove
    
    cd /vagrant
    sudo pip install -r requirements.txt  
    sudo -H pip install thefuck
    echo 'eval $(thefuck --alias)' >> ~/.bashrc
  SHELL
end
